<?php
$categories = $this->getCategoryCollection();
$categoryViewUrl = Mage::getUrl('blog/index/categoryview');
?>
<h1>Categories page</h1>
<?php foreach ($categories as $item): ?>
    <h2>
        <a href="<?php echo $categoryViewUrl; ?>?id=<?php echo $item->getCategoryId(); ?>">
            <?php echo $item->getCategoryName(); ?>
        </a>
    </h2>
<div> <?php echo $item->getCategoryDescription(); ?></div></br>
<?php endforeach; ?>
